	;873ABasic.asm
	;September 5, 2024
	;Alex Wheelock
	;Program that uses 8 inputs from a DIP switch, that displays the corresponding number on the input onto a dot matrix display.
	;If no switch is pressed, display a 0. If port B1 is pressed then display a 1 and so on. Have the highest number have priority.
	;Repeat this in an endless loop. Use port C for the display output and port B for the DIP switch inputs.

		#INCLUDE <p16f883.inc>        		; processor specific variable definitions
		LIST      p=16f883		  	; list directive to define processor
		errorlevel -302,-207,-305,-206,-203	;suppress "not in bank 0" message,  Found label after column 1,
							;Using default destination of 1 (file),  Found call to macro in column 1

		; CONFIG1
; __config 0xE0E2
 __CONFIG _CONFIG1, _FOSC_HS & _WDTE_OFF & _PWRTE_ON & _MCLRE_OFF & _CP_OFF & _CPD_OFF & _BOREN_OFF & _IESO_OFF & _FCMEN_OFF & _LVP_OFF
; CONFIG2
; __config 0xFFFF
 __CONFIG _CONFIG2, _BOR4V_BOR40V & _WRT_OFF


;******************************************		
;Define Constants
;******************************************

#Define		FOSC		D'4000'			;Oscillator Clock in KHz This must be filled

;******************************************		
;Define Variable Registers
;******************************************

 	COUNT1	EQU	0x20
	COUNT2	EQU	0x21
	COUNT3	EQU	0x22
	COUNT4	EQU	0x23
	COUNT5	EQU	0x24
	STEP	EQU	0x25
	LEG_1	EQU	0x26
		
;******************************************		
;Interupt Vectors
;******************************************
		ORG H'000'					
		GOTO SETUP					;RESET CONDITION GOTO SETUP

;******************************************
;SETUP ROUTINE
;******************************************
SETUP
;*** SFR SETUP **********
 
		
;*** SET OPTION_REG: ****
		
		BANKSEL OPTION_REG
		BCF		OPTION_REG, PS0		;\\
		BCF		OPTION_REG, PS1		; >>PRESCALER RATIO SET 1:1
		BCF		OPTION_REG, PS2		;//
		BSF		OPTION_REG, PSA		;PRESCALER ASSIGNED TO WDT 
		BCF		OPTION_REG, T0SE	;TMR0 EDGE SET RISING
		BCF		OPTION_REG, T0CS	;TMR0 CLOCK SOURCE SET TO INTERNAL
		BSF		OPTION_REG, INTEDG	;RB0/INT SET TO RISING EDGE
		BSF		OPTION_REG, 7		;PORTB PULLUP ENABLED
		
;*** SET INTCON REG: ****
		
		BANKSEL INTCON
		BCF		INTCON, RBIE		;DISABLE PORT B CHANGE INTERUPT 
		BCF		INTCON, INTE		;DISABLE RB0/INT EXTERNAL INTERUPT
		BCF		INTCON, TMR0IE		;DISABLE TMR0 INTERUPT (ENABLED IN MAIN PROGRAM)
		BSF		INTCON, PEIE		;ENABLE PERIPHERAL INTERUPTS
		BSF		INTCON, GIE		;ENABLE ALL UNMASKED INTERUPTS
		
;*** SET PIE1 REG: *****
		
		BANKSEL PIE1
		BCF		PIE1, TMR1IE		;DISABLE TMR1 INTERUPT
		BCF		PIE1, TMR2IE		;DISABLE TMR2 INTERUPT POR PWM
		BCF		PIE1, CCP1IE		;DISABLE CCP1 INTERUPT
		BCF		PIE1, SSPIE		;DISABLE SSP INTERUPT
		BCF		PIE1, TXIE		;DISABLE USART TRANSMIT INTERUPT
		BCF		PIE1, RCIE		;DISABLE USART RECIEVE INTERUPT
		BCF		PIE1, ADIE		;DISABLE A/D INTERUPT
		BCF		PIE1, 7			;DISABLE PSP INTERUPT
		
;*** SET CCP1CON REG: **
		
		BANKSEL CCP1CON
		MOVLW	H'00'				;DISABLE PWM & CCP
		MOVWF	CCP1CON

;*** TIMER 1 SETUP *****
		
		BANKSEL T1CON
		CLRF T1CON				;DISABLE TIMER 1

;*** TIMER 2 SETUP *****

		BANKSEL T2CON
		CLRF	T2CON				;DISABLE TIMER 2
 
;*** PORT A SETUP **** PORT A SET AS LOGIC OUTPUT (NOT USED)

		BANKSEL PORTA
		CLRF	PORTA				;INIT PORT A
		BANKSEL	TRISA
		MOVLW	H'30'				;SET PORT A AS OUTPUT
		MOVWF	TRISA
		
;*** PORT B SETUP **** PORT B USED AS LOGIC INPUT
		
		BANKSEL PORTB
		CLRF	PORTB				;INIT PORT B
		BANKSEL	TRISB
		MOVLW	H'FF'				;SET PORT B AS INPUT
		MOVWF	TRISB
		BANKSEL ANSELH
		MOVLW	H'00'				;DISABLES ANALOG INPUT TO ENSURE THAT IT IS A DIGITAL INPUT
		MOVWF	ANSELH
		
;*** PORT C SETUP **** PORT C USED AS LOGIC OUTPUT TO DRIVE DOT MATRIX
		
		BANKSEL PORTC
		CLRF PORTC				;INIT PORTC
		BANKSEL	TRISC
		MOVLW	H'00'
		MOVWF	TRISC				;SET PORT C AS OUTPUT
		
		GOTO	MAIN				;END OF SETUP ROUTINE

;******************************************
;Main Code
;******************************************
MAIN	
		BANKSEL	PORTB
		BTFSC	PORTB,7				;TEST IF RB7 IS TRUE, SKIP NEXT COMMAND IF FALSE
		GOTO	SETRC7				;
		BTFSC	PORTB,6				;TEST IF RB6 IS TRUE, SKIP NEXT COMMAND IF FALSE
		GOTO	SETRC6				;
		BTFSC	PORTB,5				;TEST IF RB5 IS TRUE, SKIP NEXT COMMAND IF FALSE
		GOTO	SETRC5				;
		BTFSC	PORTB,4				;TEST IF RB4 IS TRUE, SKIP NEXT COMMAND IF FALSE
		GOTO	SETRC4				;
		BTFSC	PORTB,3				;TEST IF RB3 IS TRUE, SKIP NEXT COMMAND IF FALSE
		GOTO	SETRC3				;
		BTFSC	PORTB,2				;TEST IF RB2 IS TRUE, SKIP NEXT COMMAND IF FALSE
		GOTO	SETRC2				;
		BTFSC	PORTB,1				;TEST IF RB1 IS TRUE, SKIP NEXT COMMAND IF FALSE
		GOTO	SETRC1				;
		BTFSC	PORTB,0				;TEST IF RB0 IS TRUE, SKIP NEXT COMMAND IF FALSE
		GOTO	SETRC0				;
		BANKSEL	PORTC 				;RB0 WAS FALSE, SET PORTC TO GIVE A 0 ON DOT MATRIX
		MOVLW	H'30'				;
		MOVWF	PORTC				;WRITE 30h (ASCII 0) TO PORTC OUTPUTS
		GOTO	MAIN				;RESTART LOOP
	SETRC7				
		BANKSEL	PORTC				;RB7 WAS TRUE, SET PORTC TO GIVE AN 8 ON DOT MATRIX
		MOVLW	H'38'				;
		MOVWF	PORTC				;WRITE 38h (ASCII 8) TO PORTC OUTPUTS
		GOTO	MAIN				;RESTART LOOP
	SETRC6
		BANKSEL	PORTC				;RB6 WAS TRUE, SET PORTC TO GIVE A 7 ON DOT MATRIX
		MOVLW	H'37'				;
		MOVWF	PORTC				;WRITE 37h (ASCII 7) TO PORTC OUTPUTS
		GOTO	MAIN				;RESTART LOOP
	SETRC5
		BANKSEL	PORTC				;RB5 WAS TRUE, SET PORTC TO GIVE A 6 ON DOT MATRIX
		MOVLW	H'36'				;
		MOVWF	PORTC				;WRITE 36h (AS6II 6) TO PORTC OUTPUTS
		GOTO	MAIN				;RESTART LOOP
	SETRC4
		BANKSEL	PORTC				;RB4 WAS TRUE, SET PORTC TO GIVE A 5 ON DOT MATRIX
		MOVLW	H'35'				;
		MOVWF	PORTC				;WRITE 35h (ASCII 5) TO PORTC OUTPUTS
		GOTO	MAIN				;RESTART LOOP
	SETRC3
		BANKSEL	PORTC				;RB3 WAS TRUE, SET PORTC TO GIVE A 4 ON DOT MATRIX
		MOVLW	H'34'				;
		MOVWF	PORTC				;WRITE 34h (ASCII 4) TO PORTC OUTPUTS
		GOTO	MAIN				;RESTART LOOP
	SETRC2
		BANKSEL	PORTC				;RB2 WAS TRUE, SET PORTC TO GIVE A 3 ON DOT MATRIX
		MOVLW	H'33'				;
		MOVWF	PORTC				;WRITE 33h (ASCII 3) TO PORTC OUTPUTS
		GOTO	MAIN				;RESTART LOOP
	SETRC1
		BANKSEL	PORTC				;RB1 WAS TRUE, SET PORTC TO GIVE A 2 ON DOT MATRIX
		MOVLW	H'32'				;
		MOVWF	PORTC				;WRITE 32h (ASCII 2) TO PORTC OUTPUTS
		GOTO	MAIN				;RESTART LOOP
	SETRC0
		BANKSEL	PORTC				;RB0 WAS TRUE, SET PORTC TO GIVE AN 1 ON DOT MATRIX
		MOVLW	H'31'				;
		MOVWF	PORTC				;WRITE 31h (ASCII 1) TO PORTC OUTPUTS
		GOTO	MAIN				;RESTART LOOP
		
END
		
;******************************************		
;END PROGRAM DIRECTIVE
;******************************************