	;Keypad.asm
	;September 6, 2024
	;Alex Wheelock
	;Program that uses a hex keypad with inputs from 0 to F on PORTB. It then converts the input from the keypad into the correct 
	;corresponding character to be displayed on a dot matrix display.

		#INCLUDE <p16f883.inc>        		; processor specific variable definitions
		LIST      p=16f883		  	; list directive to define processor
		errorlevel -302,-207,-305,-206,-203	;suppress "not in bank 0" message,  Found label after column 1,
							;Using default destination of 1 (file),  Found call to macro in column 1

		; CONFIG1
; __config 0xE0E2
 __CONFIG _CONFIG1, _FOSC_HS & _WDTE_OFF & _PWRTE_ON & _MCLRE_OFF & _CP_OFF & _CPD_OFF & _BOREN_OFF & _IESO_OFF & _FCMEN_OFF & _LVP_OFF
; CONFIG2
; __config 0xFFFF
 __CONFIG _CONFIG2, _BOR4V_BOR40V & _WRT_OFF


;******************************************		
;Define Constants
;******************************************

#Define		FOSC		D'4000'			;Oscillator Clock in KHz This must be filled

;******************************************		
;Define Variable Registers
;******************************************

 	COUNT1	EQU	0x20
	COUNT2	EQU	0x21
	COUNT3	EQU	0x22
	COUNT4	EQU	0x23
	COUNT5	EQU	0x24
	STEP	EQU	0x25
	LEG_1	EQU	0x26
		
;******************************************		
;Interupt Vectors
;******************************************
		ORG H'000'					
		GOTO SETUP					;RESET CONDITION GOTO SETUP

;******************************************
;SETUP ROUTINE
;******************************************
SETUP
;*** SFR SETUP **********
 
		
;*** SET OPTION_REG: ****
		
		BANKSEL OPTION_REG
		BCF		OPTION_REG, PS0		;\\
		BCF		OPTION_REG, PS1		; >>PRESCALER RATIO SET 1:1
		BCF		OPTION_REG, PS2		;//
		BSF		OPTION_REG, PSA		;PRESCALER ASSIGNED TO WDT 
		BCF		OPTION_REG, T0SE	;TMR0 EDGE SET RISING
		BCF		OPTION_REG, T0CS	;TMR0 CLOCK SOURCE SET TO INTERNAL
		BSF		OPTION_REG, INTEDG	;RB0/INT SET TO RISING EDGE
		BSF		OPTION_REG, 7		;PORTB PULLUP ENABLED
		
;*** SET INTCON REG: ****
		
		BANKSEL INTCON
		BCF		INTCON, RBIE		;DISABLE PORT B CHANGE INTERUPT 
		BCF		INTCON, INTE		;DISABLE RB0/INT EXTERNAL INTERUPT
		BCF		INTCON, TMR0IE		;DISABLE TMR0 INTERUPT (ENABLED IN MAIN PROGRAM)
		BSF		INTCON, PEIE		;ENABLE PERIPHERAL INTERUPTS
		BSF		INTCON, GIE		;ENABLE ALL UNMASKED INTERUPTS
		
;*** SET PIE1 REG: *****
		
		BANKSEL PIE1
		BCF		PIE1, TMR1IE		;DISABLE TMR1 INTERUPT
		BCF		PIE1, TMR2IE		;DISABLE TMR2 INTERUPT POR PWM
		BCF		PIE1, CCP1IE		;DISABLE CCP1 INTERUPT
		BCF		PIE1, SSPIE		;DISABLE SSP INTERUPT
		BCF		PIE1, TXIE		;DISABLE USART TRANSMIT INTERUPT
		BCF		PIE1, RCIE		;DISABLE USART RECIEVE INTERUPT
		BCF		PIE1, ADIE		;DISABLE A/D INTERUPT
		BCF		PIE1, 7			;DISABLE PSP INTERUPT
		
;*** SET CCP1CON REG: **
		
		BANKSEL CCP1CON
		MOVLW	H'00'				;DISABLE PWM & CCP
		MOVWF	CCP1CON

;*** TIMER 1 SETUP *****
		
		BANKSEL T1CON
		CLRF T1CON				;DISABLE TIMER 1

;*** TIMER 2 SETUP *****

		BANKSEL T2CON
		CLRF	T2CON				;DISABLE TIMER 2
 
;*** PORT A SETUP **** PORT A SET AS LOGIC OUTPUT (NOT USED)

		BANKSEL PORTA
		CLRF	PORTA				;INIT PORT A
		BANKSEL	TRISA
		MOVLW	H'30'				;SET PORT A AS OUTPUT
		MOVWF	TRISA
		
;*** PORT B SETUP **** PORT B USED AS LOGIC INPUT FROM KEYPAD
		
		BANKSEL PORTB
		CLRF	PORTB				;INIT PORT B
		BANKSEL	TRISB
		MOVLW	H'FF'				;SET PORT B AS INPUT
		MOVWF	TRISB
		BANKSEL ANSELH
		MOVLW	H'00'				;DISABLES ANALOG INPUT TO ENSURE THAT IT IS A DIGITAL INPUT
		MOVWF	ANSELH
		
;*** PORT C SETUP **** PORT C USED AS LOGIC OUTPUT TO DRIVE DOT MATRIX
		
		BANKSEL PORTC
		CLRF PORTC				;INIT PORTC
		BANKSEL	TRISC
		MOVLW	H'00'
		MOVWF	TRISC				;SET PORT C AS OUTPUT
		
		GOTO	MAIN				;END OF SETUP ROUTINE

;******************************************
;Main Code
;******************************************
MAIN							;TEST INPUTS FROM GREATEST TO LEAST FROM KEYPAD
		BANKSEL	PORTB				
		BTFSC	PORTB,0				;TEST RBO, SKIP TO NEXT BIT TEST IF FALSE
		GOTO	TEST_CTOF			;RB0 TRUE, TEST UPPER NIBBLE
		BTFSC	PORTB,1				;TEST RB1, SKIP TO NEXT BIT TEST IF FALSE
		GOTO	TEST_8TOB			;RB1 TRUE, TEST UPPER NIBBLE
		BTFSC	PORTB,2				;TEST RB2, SKIP TO NEXT BIT TEST IF FALSE
		GOTO	TEST_4TO7			;RB2 TRUE, TEST UPPER NIBBLE
		BTFSC	PORTB,3				;TEST RB3, SKIP TO NEXT BIT TEST IF FALSE
		GOTO	TEST_0TO3			;RB3 TRUE, TEST UPPER NIBBLE
		BANKSEL	PORTC 				;0-F WERE NOT PRESSED
		MOVLW	H'20'				;
		MOVWF	PORTC				;SET PORTC OUTPUT TO 20h TO DISPLAY NOTHING ONTO THE DOT MATRIX DISPLAY
		GOTO	MAIN				;RESTART LOOP			
		
	    TEST_CTOF					;
		BTFSC	PORTB,4				;TEST RB4, SKIP TO NEXT BIT TEST IF FALSE
		GOTO	SET_F				;RB4 TRUE, SET OUTPUT TO F
		BTFSC	PORTB,5				;TEST RB5, SKIP TO NEXT BIT TEST IF FALSE
		GOTO	SET_E				;RB5 TRUE, SET OUTPUT TO E
		BTFSC	PORTB,6				;TEST RB6, SKIP TO NEXT BIT TEST IF FALSE
		GOTO	SET_D				;RB6 TRUE, SET OUTPUT TO D
		GOTO	SET_C				;ALL OTHER BITS IN UPPER NIBBLE FALSE, INPUT HAS TO BE C
	    TEST_8TOB
		BTFSC	PORTB,4				;TEST RB4, SKIP TO NEXT BIT TEST IF FALSE
		GOTO	SET_B				;RB4 TRUE, SET OUTPUT TO B
		BTFSC	PORTB,5				;TEST RB5, SKIP TO NEXT BIT TEST IF FALSE
		GOTO	SET_A				;RB5 TRUE, SET OUTPUT TO A
		BTFSC	PORTB,6				;TEST RB6, SKIP TO NEXT BIT TEST IF FALSE
		GOTO	SET_9				;RB6 TRUE, SET OUTPUT TO 9
		GOTO	SET_8				;ALL OTHER BITS IN UPPER NIBBLE FALSE, INPUT HAS TO BE 8
	    TEST_4TO7
	    	BTFSC	PORTB,4				;TEST RB4, SKIP TO NEXT BIT TEST IF FALSE
		GOTO	SET_7				;RB4 TRUE, SET OUTPUT TO 7
		BTFSC	PORTB,5				;TEST RB5, SKIP TO NEXT BIT TEST IF FALSE
		GOTO	SET_6				;RB5 TRUE, SET OUTPUT TO 6
		BTFSC	PORTB,6				;TEST RB6, SKIP TO NEXT BIT TEST IF FALSE
		GOTO	SET_5				;RB6 TRUE, SET OUTPUT TO 5
		GOTO	SET_4				;ALL OTHER BITS IN UPPER NIBBLE FALSE, INPUT HAS TO BE 4
	    TEST_0TO3
		BTFSC	PORTB,4				;TEST RB4, SKIP TO NEXT BIT TEST IF FALSE
		GOTO	SET_3				;RB4 TRUE, SET OUTPUT TO 3
		BTFSC	PORTB,5				;TEST RB5, SKIP TO NEXT BIT TEST IF FALSE
		GOTO	SET_2				;RB5 TRUE, SET OUTPUT TO 2
		BTFSC	PORTB,6				;TEST RB6, SKIP TO NEXT BIT TEST IF FALSE
		GOTO	SET_1				;RB6 TRUE, SET OUTPUT TO 1
		GOTO	SET_0				;ALL OTHER BITS IN UPPER NIBBLE FALSE, INPUT HAS TO BE 0
		
	    SET_F				
		BANKSEL	PORTC				;
		MOVLW	H'46'				;
		MOVWF	PORTC				;SET PORTC OUTPUT TO 46h TO DISPLAY "F" ONTO THE DOT MATRIX DISPLAY
		GOTO	MAIN				;RESTART LOOP
	    SET_E
		BANKSEL	PORTC				;
		MOVLW	H'45'				;
		MOVWF	PORTC				;SET PORTC OUTPUT TO 45h TO DISPLAY "E" ONTO THE DOT MATRIX DISPLAY
		GOTO	MAIN				;RESTART LOOP
	    SET_D
		BANKSEL	PORTC				;
		MOVLW	H'44'				;
		MOVWF	PORTC				;SET PORTC OUTPUT TO 44h TO DISPLAY "D" ONTO THE DOT MATRIX DISPLAY
		GOTO	MAIN				;RESTART LOOP
	    SET_C
	    	BANKSEL	PORTC				;
		MOVLW	H'43'				;
		MOVWF	PORTC				;SET PORTC OUTPUT TO 43h TO DISPLAY "C" ONTO THE DOT MATRIX DISPLAY
		GOTO	MAIN				;RESTART LOOP
	    SET_B
		BANKSEL	PORTC				;
		MOVLW	H'42'				;
		MOVWF	PORTC				;SET PORTC OUTPUT TO 42h TO DISPLAY "B" ONTO THE DOT MATRIX DISPLAY
		GOTO	MAIN				;RESTART LOOP
	    SET_A
		BANKSEL	PORTC				;
		MOVLW	H'41'				;
		MOVWF	PORTC				;SET PORTC OUTPUT TO 41h TO DISPLAY "A" ONTO THE DOT MATRIX DISPLAY
		GOTO	MAIN				;RESTART LOOP
	    SET_9
		BANKSEL	PORTC				;
		MOVLW	H'39'				;
		MOVWF	PORTC				;SET PORTC OUTPUT TO 39h TO DISPLAY "9" ONTO THE DOT MATRIX DISPLAY
		GOTO	MAIN				;RESTART LOOP
	    SET_8
		BANKSEL	PORTC				;
		MOVLW	H'38'				;
		MOVWF	PORTC				;SET PORTC OUTPUT TO 38h TO DISPLAY "8" ONTO THE DOT MATRIX DISPLAY
		GOTO	MAIN				;RESTART LOOP
	    SET_7
		BANKSEL	PORTC				;
		MOVLW	H'37'				;
		MOVWF	PORTC				;SET PORTC OUTPUT TO 37h TO DISPLAY "7" ONTO THE DOT MATRIX DISPLAY
		GOTO	MAIN				;RESTART LOOP
	    SET_6
		BANKSEL	PORTC				;
		MOVLW	H'36'				;
		MOVWF	PORTC				;SET PORTC OUTPUT TO 36h TO DISPLAY "6" ONTO THE DOT MATRIX DISPLAY
		GOTO	MAIN				;RESTART LOOP
	    SET_5
		BANKSEL	PORTC				;
		MOVLW	H'35'				;
		MOVWF	PORTC				;SET PORTC OUTPUT TO 35h TO DISPLAY "5" ONTO THE DOT MATRIX DISPLAY
		GOTO	MAIN				;RESTART LOOP
	    SET_4
		BANKSEL	PORTC				;
		MOVLW	H'34'				;
		MOVWF	PORTC				;SET PORTC OUTPUT TO 34h TO DISPLAY "4" ONTO THE DOT MATRIX DISPLAY
		GOTO	MAIN				;RESTART LOOP
	    SET_3
		BANKSEL	PORTC				;
		MOVLW	H'33'				;
		MOVWF	PORTC				;SET PORTC OUTPUT TO 33h TO DISPLAY "3" ONTO THE DOT MATRIX DISPLAY
		GOTO	MAIN				;RESTART LOOP	
	    SET_2
		BANKSEL	PORTC				;
		MOVLW	H'32'				;
		MOVWF	PORTC				;SET PORTC OUTPUT TO 32h TO DISPLAY "2" ONTO THE DOT MATRIX DISPLAY
		GOTO	MAIN				;RESTART LOOP
	    SET_1
		BANKSEL	PORTC				;
		MOVLW	H'31'				;
		MOVWF	PORTC				;SET PORTC OUTPUT TO 31h TO DISPLAY "1" ONTO THE DOT MATRIX DISPLAY
		GOTO	MAIN				;RESTART LOOP
	    SET_0
		BANKSEL	PORTC				;
		MOVLW	H'30'				;
		MOVWF	PORTC				;SET PORTC OUTPUT TO 30h TO DISPLAY "0" ONTO THE DOT MATRIX DISPLAY
		GOTO	MAIN				;RESTART LOOP	
END

;******************************************		
;END PROGRAM DIRECTIVE
;******************************************